apiVersion: apps/v1
kind: Deployment
metadata:
  name: face_detection
spec:
  selector:
    matchLabels:
      app: face_detection
  replicas: 1 # tells deployment to run 1 pods matching the template
  template:
    metadata:
      labels:
        app: face_detection
    spec:
      containers:
      - name: face_detection
        image: rubyhan/face_detection:v1
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /dev/video0
          name: dev-video0
      volumes:
      - name: dev-video0
        hostPath:
          path: /dev/video0
