FROM ubuntu:latest

ENV DEBIAN_FRONTEND noninteractive
ENV PYTHONUNBUFFERED=1
WORKDIR /app
RUN export OPENBLAS_CORETYPE=ARMV8
RUN apt-get update && apt-get install -y python3 python3-pip python3-opencv

RUN pip3 install paho-mqtt
RUN pip3 install numpy
RUN pip3 install opencv-python
RUN pip3 install boto3

COPY credentials.py ./
COPY processor.py ./

CMD python3 /app/processor.py