apiVersion: apps/v1
kind: Deployment
metadata:
  name: face-identifier
spec:
  selector:
    matchLabels:
      app: face-identifier
  replicas: 1 # tells deployment to run 1 pods matching the template
  template:
    metadata:
      labels:
        app: face-identifier
    spec:
      containers:
      - name: face-identifier
        image: lensgerrit/publisher_fp:v2 # lensgerrit/face_identifier:v2
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /dev/video0
          name: dev-video0
      volumes:
      - name: dev-video0
        hostPath:
          path: /dev/video0
