apiVersion: apps/v1
kind: Deployment
metadata:
  name: publisher
spec:
  selector:
    matchLabels:
      app: publisher
  replicas: 1 # tells deployment to run 1 pods matching the template
  template:
    metadata:
      labels:
        app: publisher
    spec:
      containers:
      - name: publisher
        image: lensgerrit/publisher_fp:v4 # lensgerrit/publisher_fp:v3
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /dev/video0
          name: dev-video0
        - mountPath: /home/gerritlensink/Desktop/w251/final_project/MNIST-Skin-Cancer-with-Jetson/Pipeline/Image_Folder/Edge/
          name: photo-dir
      volumes:
      - name: dev-video0
        hostPath:
          path: /dev/video0
      - name: photo-dir
        hostPath:
          path: /home/gerritlensink/Desktop/w251/final_project/MNIST-Skin-Cancer-with-Jetson/Pipeline/Image_Folder/Edge/
